"""The frequency-space mesh loaders (mode=trianglefreq and mode=tetfreq).

These modes read a velocity given as Fourier modes in time,

    u(x, t) = sum_k a_k cos(omega0 (k t + t_k)) u_k(x),   omega0 = 2 pi / tau,

with one dolfin checkpoint per mode k, and one line of freqstamps.dat per mode
holding t_k, a_k and that mode's file, in order of k. Nothing else in the suite
checks that the weights are assembled as written: a swapped a_k and t_k, a
phase multiplied by k, a wrong sign in omega0 or a mode read in the wrong order
all still give a smooth field that advects particles.

So both cases here hold modes that are polynomials of degree two, which P2
represents exactly. The velocity, the pressure and the whole velocity gradient
then have a closed form at any point and time, and the probed values must match
it to round-off. The shipped sine_trianglefreq_p2 cannot serve for that: sin is
not a P2 polynomial, so its interpolation error would hide everything smaller.
The triangle case is therefore built here; the tet case is the shipped
data_example/sine_tetfreq_p2, generated by conftest.

Each case is periodic in x only, and the velocity components across the
non-periodic faces vanish there, so a tracer started inside stays inside. That
is the second thing checked: RK4 runs and no particle leaves the box.
"""

import os
import shutil
import subprocess

import numpy as np
import pytest

from paths import REPO, app, built_with_dolfin

INTERPOL = app("interpol")
TRACERS = app("tracers")

# the shipped parameter file of each mode's example, used to ask the apps
# whether they know the mode at all
SHIPPED = {mode: os.path.join(REPO, "data_example", folder, "dolfin_params.dat")
           for mode, folder in (("trianglefreq", "sine_trianglefreq_p2"),
                                ("tetfreq", "sine_tetfreq_p2"))}

pytestmark = pytest.mark.skipif(not built_with_dolfin(),
                                reason="partrac was built without dolfin")

# the base period both cases declare as tau
TAU = 1.0

# mode k -> (time shift t_k, amplitude a_k), in the order freqstamps.dat lists
# them. k = 0 is the time-independent mean.
STAMPS = [(0.0, 1.0), (0.125, 0.7), (-0.25, 0.4)]

# probe times: none a multiple of tau, so every mode carries a different weight
TIMES = [0.137, 0.362, 1.311]


def weights(t):
    """The weight a_k cos(omega0 (k t + t_k)) of each mode at time t."""
    omega0 = 2 * np.pi / TAU
    return [a * np.cos(omega0 * (k * t + t_k)) for k, (t_k, a) in enumerate(STAMPS)]


# --- the two cases and their closed forms --------------------------------------

# The 2D modes, as the case built below writes them: u_k, then p_k.
TRIANGLE_MODES = [
    (("1 + x[1]*x[1]", "0.2*x[1]*(1-x[1])"), "x[1]"),
    (("x[1] - 0.5", "0.0"), "2*x[1]"),
    (("x[1]*(1-x[1])", "0.1*x[1]*(1-x[1])"), "0.5*x[1]"),
]


def triangle_exact(v, t):
    """What mode=trianglefreq must report at the probe points v and time t."""
    y = v["y"]
    w = weights(t)
    shear = 0.2 * w[0] + 0.1 * w[2]     # the common factor of u_y
    return {
        "ux": w[0] * (1 + y * y) + w[1] * (y - 0.5) + w[2] * y * (1 - y),
        "uy": shear * y * (1 - y),
        "uz": np.zeros_like(y),
        "p": w[0] * y + w[1] * 2 * y + w[2] * 0.5 * y,
        "uxx": np.zeros_like(y),
        "uxy": 2 * w[0] * y + w[1] + w[2] * (1 - 2 * y),
        "uyx": np.zeros_like(y),
        "uyy": shear * (1 - 2 * y),
    }


def tet_exact(v, t):
    """What mode=tetfreq must report at the probe points v and time t.

    This repeats, independently, the modes data_example/sine_tetfreq_p2 writes.
    """
    y, z = v["y"], v["z"]
    w = weights(t)
    shear_y = 0.2 * w[0] + 0.1 * w[2]
    shear_z = 0.3 * w[1] - 0.2 * w[2]
    zero = np.zeros_like(y)
    return {
        "ux": w[0] * (1 + y * z) + w[1] * z * (1 - z) + w[2] * (y - 0.5),
        "uy": shear_y * y * (1 - y),
        "uz": shear_z * z * (1 - z),
        "p": w[0] * (y + 2 * z) + w[1] * z + w[2] * y,
        "uxx": zero, "uxy": w[0] * z + w[2], "uxz": w[0] * y + w[1] * (1 - 2 * z),
        "uyx": zero, "uyy": shear_y * (1 - 2 * y), "uyz": zero,
        "uzx": zero, "uzy": zero, "uzz": shear_z * (1 - 2 * z),
    }


@pytest.fixture(scope="session")
def triangle_freq_dir(tmp_path_factory):
    """A triangle case for mode=trianglefreq whose modes P2 holds exactly.

    Built the way data_example/sine_tetfreq_p2 builds its tet counterpart: the
    velocity space is constrained by a periodic subdomain matching the
    periodic_x it declares, and each mode is written as one dolfin checkpoint
    named in freqstamps.dat.
    """
    df = pytest.importorskip("dolfin", reason="writing the case needs dolfin")
    d = tmp_path_factory.mktemp("trianglefreq_exact")

    class PBC(df.SubDomain):
        """x = 0 is the master face; x = 1 maps onto it."""
        def inside(self, x, on):
            return bool(on and df.near(x[0], 0) and not df.near(x[0], 1))

        def map(self, x, y):
            y[0] = x[0] - 1 if df.near(x[0], 1) else x[0]
            y[1] = x[1]

    mesh = df.UnitSquareMesh(8, 8)
    pbc = PBC()
    V = df.VectorFunctionSpace(mesh, "CG", 2, constrained_domain=pbc)
    P = df.FunctionSpace(mesh, "CG", 1, constrained_domain=pbc)

    with df.HDF5File(mesh.mpi_comm(), str(d / "mesh.h5"), "w") as f:
        f.write(mesh, "mesh")
    lines = []
    for k, ((t_k, a_k), (u_expr, p_expr)) in enumerate(zip(STAMPS, TRIANGLE_MODES)):
        with df.HDF5File(mesh.mpi_comm(), str(d / ("up_%d.h5" % k)), "w") as f:
            f.write(df.interpolate(df.Expression(u_expr, degree=2), V), "u")
            f.write(df.interpolate(df.Expression(p_expr, degree=1), P), "p")
        lines.append("%r %r up_%d.h5" % (t_k, a_k, k))
    (d / "freqstamps.dat").write_text("\n".join(lines) + "\n")
    (d / "dolfin_params.dat").write_text(
        "velocity_space=P2\npressure_space=P1\nfreqstamps=freqstamps.dat\n"
        "mesh=mesh.h5\nperiodic_x=true\nperiodic_y=false\nperiodic_z=false\n"
        "rho=1.0\ntau=%r\nt_min=0\nt_max=1e8\n" % TAU)
    return d


# mode -> (fixture giving the shipped or built case, closed form, the centre a
# run starts from, the directions a particle must not leave)
CASES = {
    "trianglefreq": (triangle_exact, "x0=0.5 y0=0.5 z0=0", ["y"]),
    "tetfreq": (tet_exact, "x0=0.5 y0=0.5 z0=0.5", ["y", "z"]),
}


@pytest.fixture(params=sorted(CASES), ids=sorted(CASES))
def freq_case(request, tmp_path, mesh_dir, triangle_freq_dir):
    """(mode, a private copy of its case, closed form, start point, bounded directions).

    The copy is private because the apps write their output beside the input.
    """
    mode = request.param
    require_mode(mode)
    src = triangle_freq_dir if mode == "trianglefreq" else mesh_dir("tetfreq")
    d = tmp_path / "case"
    d.mkdir()
    for f in os.listdir(src):
        if f != "generate_up.py":
            shutil.copy(os.path.join(src, f), d / f)
    cfg = d / "dolfin_params.dat"
    exact, centre, bounded = CASES[mode]
    return mode, d, cfg, exact, centre, bounded


# --- does this build know the mode? --------------------------------------------

def require_mode(mode):
    """Skip only if the apps are not built: a build that lost a mode must fail here."""
    if not os.path.exists(INTERPOL):
        pytest.skip("interpol is not built")


# --- the tests -----------------------------------------------------------------


def probe(cfg, mode, t0, npoints=400):
    """Run interpol on the case at time t0; returns its datasets as arrays."""
    h5py = pytest.importorskip("h5py")
    r = subprocess.run([INTERPOL, str(cfg), "mode=" + mode, "Nrw=%d" % npoints,
                        "int_order=2", "t0=%r" % t0, "random=false", "seed=1",
                        "tag=t%r" % t0],
                       capture_output=True, text=True, timeout=600)
    assert r.returncode == 0, r.stdout[-800:] + r.stderr
    out = [p for p in cfg.parent.rglob("interpolation.h5part") if ("t%r" % t0) in str(p)]
    assert len(out) == 1, out
    with h5py.File(out[0], "r") as h:
        return {k: np.array(h["Step#0"][k]) for k in h["Step#0"]}


@pytest.mark.parametrize("t0", TIMES)
def test_the_frequency_sum_matches_its_closed_form(freq_case, t0):
    """The probed velocity, pressure and velocity gradient equal the sum over
    modes, to round-off, at a time that is not a whole period.

    The modes are quadratics, held exactly by P2, so any difference is in how
    the loader weights them: the amplitudes a_k, the shifts t_k, the base
    frequency omega0 = 2 pi / tau, the factor k on t, or the order the modes
    are read in.
    """
    mode, _, cfg, exact, _, _ = freq_case
    v = probe(cfg, mode, t0)
    assert len(v["x"]) > 100, "too few points landed inside to be worth comparing"
    want = exact(v, t0)
    for name, expected in want.items():
        assert np.abs(v[name] - expected).max() < 1e-10, \
            "%s at t = %g: %s is off by %g" % (mode, t0, name,
                                               np.abs(v[name] - expected).max())
    # the check can fail: the weights differ between the probe times
    assert np.abs(want["ux"]).max() > 0.1


def test_the_weights_change_with_time(freq_case):
    """The field probed at two times differs, so the mode really is unsteady.

    A loader that ignored the time, or that summed the modes with the weights
    of t = 0, would pass a single-time comparison at t = 0 and nothing else.
    """
    mode, _, cfg, _, _, _ = freq_case
    a = probe(cfg, mode, TIMES[0], npoints=200)
    b = probe(cfg, mode, TIMES[1], npoints=200)
    # the same seed draws the same points, so the fields compare point by point
    assert np.array_equal(a["x"], b["x"])
    assert np.abs(a["ux"] - b["ux"]).max() > 1e-3


def test_tracers_run_and_stay_in_the_box(freq_case):
    """tracers takes RK4 steps on the case and no particle leaves the domain.

    The velocity component across each non-periodic face is zero on that face,
    so a particle that starts inside cannot be carried out; one that appears
    outside means the field, the cell search or the periodic wrapping is wrong.
    """
    h5py = pytest.importorskip("h5py")
    mode, d, cfg, _, centre, bounded = freq_case
    if not os.path.exists(TRACERS):
        pytest.skip("tracers is not built")
    args = ("Dm=0 dt=0.005 T=0.05 Nrw=200 Nrw_max=2000 dump_intv=0.01 "
            "stat_intv=1e9 checkpoint_intv=1e9 init_mode=points_xy int_order=2 "
            "scheme=RK4 random=false seed=1").split() + centre.split()
    r = subprocess.run([TRACERS, str(cfg), "mode=" + mode] + args,
                       capture_output=True, text=True, timeout=900)
    assert r.returncode == 0, r.stdout[-800:] + r.stderr

    steps = {}
    for f in d.rglob("data_from_t*.h5"):
        with h5py.File(f, "r") as h:
            for k in h:
                steps[float(k)] = np.array(h[k]["points"])
    assert len(steps) > 2, "the run wrote too few dumps to say anything"
    first, last = steps[min(steps)], steps[max(steps)]
    assert np.isfinite(last).all()
    assert np.abs(last - first).max() > 1e-4, "nothing moved"
    for name in bounded:
        col = last[:, "xyz".index(name)]
        assert col.min() > -1e-9 and col.max() < 1 + 1e-9, \
            "%s: a particle left the box along %s: %g to %g" % (mode, name,
                                                                col.min(), col.max())
