# partrac_add_app(<target> SOURCE <file> [NEEDS_DOLFIN])
function(partrac_add_app name)
  cmake_parse_arguments(APP "NEEDS_DOLFIN" "SOURCE" "" ${ARGN})
  if (APP_NEEDS_DOLFIN AND NOT PARTRAC_ENABLE_DOLFIN)
    message(STATUS "Skipping app ${name}: needs dolfin.")
    return()
  endif()

  add_executable(${name} ${APP_SOURCE})
  target_link_libraries(${name} PRIVATE ${PROJECT_NAME}_core)

  # in the build tree, so two configurations can coexist
  set_target_properties(${name} PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin/")
  install(TARGETS ${name} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endfunction()

# Retired app name: TARGET with ARGS before the caller's
function(partrac_add_wrapper name)
  cmake_parse_arguments(W "" "TARGET" "ARGS;RENAME;COPY;DROP" ${ARGN})
  if (NOT TARGET ${W_TARGET})
    message(STATUS "Skipping wrapper ${name}: ${W_TARGET} is not built.")
    return()
  endif()
  set(WRAPPER_NAME ${name})
  set(WRAPPER_TARGET ${W_TARGET})
  string(REPLACE ";" " " WRAPPER_ARGS_TEXT "${W_ARGS}")
  set(WRAPPER_ARGS_CODE "")
  foreach(a ${W_ARGS})
    string(APPEND WRAPPER_ARGS_CODE "\"${a}\", ")
  endforeach()
  # old=new pairs: RENAME replaces, COPY duplicates, DROP removes
  foreach(kind RENAME COPY)
    set(WRAPPER_${kind}_CODE "")
    foreach(a ${W_${kind}})
      string(REPLACE "=" "\", \"" pair "${a}")
      string(APPEND WRAPPER_${kind}_CODE "{\"${pair}\"}, ")
    endforeach()
  endforeach()
  set(WRAPPER_DROP_CODE "")
  foreach(a ${W_DROP})
    string(APPEND WRAPPER_DROP_CODE "\"${a}\", ")
  endforeach()
  if (W_RENAME OR W_COPY OR W_DROP)
    string(APPEND WRAPPER_ARGS_TEXT " (renamed: ${W_RENAME}; copied: ${W_COPY}; dropped: ${W_DROP})")
  endif()
  set(src ${PROJECT_BINARY_DIR}/wrappers/${name}.cpp)
  configure_file(${PROJECT_SOURCE_DIR}/apps/wrapper/wrapper.cpp.in ${src} @ONLY)
  add_executable(${name} ${src})
  target_compile_features(${name} PRIVATE cxx_std_17)
  add_dependencies(${name} ${W_TARGET})
  set_target_properties(${name} PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin/")
  install(TARGETS ${name} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endfunction()
