ffc -l dolfin P1_2.ufl 
ffc -l dolfin P1_3.ufl 
ffc -l dolfin P2_2.ufl 
ffc -l dolfin P2_3.ufl 
ffc -l dolfin P3_2.ufl 
ffc -l dolfin P3_3.ufl
ffc -l dolfin vP1_2.ufl 
ffc -l dolfin vP1_3.ufl 
ffc -l dolfin vP2_2.ufl 
ffc -l dolfin vP2_3.ufl 
ffc -l dolfin vP3_2.ufl 
ffc -l dolfin vP3_3.ufl
ffc -l dolfin Q1_2.ufl